# Generated by Django 5.2.8 on 2025-12-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('grade', models.IntegerField(default=0)),
            ],
        ),
    ]
