# Generated by Django 5.2.8 on 2025-12-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_review_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20)),
                ('email1', models.EmailField(max_length=254)),
                ('email2', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
            ],
            options={
                'verbose_name': "a'loqa ma'lumotlari",
                'verbose_name_plural': "a'loqa ma'lumotlari",
            },
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'bemor qaydlari', 'verbose_name_plural': 'bemor qaydlari'},
        ),
    ]
