# Generated by Django 5.2.8 on 2025-12-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_infocontact_alter_review_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=155)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField(max_length=550)),
            ],
        ),
    ]
