# Generated by Django 5.2.8 on 2025-12-02 06:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_sendmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
