# Generated by Django 5.2.8 on 2025-12-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0005_sendmessage_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('chat_id', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'telegram admin',
                'verbose_name_plural': 'telegram_adminlari',
            },
        ),
        migrations.AlterModelOptions(
            name='sendmessage',
            options={'verbose_name': 'habar', 'verbose_name_plural': 'habarlar'},
        ),
    ]
