# Generated by Django 5.2.8 on 2025-12-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0006_tgadmin_alter_sendmessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocontact',
            name='address2',
            field=models.TextField(blank=True),
        ),
    ]
