# Generated by Django 5.2.8 on 2025-12-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0007_infocontact_address2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infocontact',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='infocontact',
            name='address2',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='infocontact',
            name='phone1',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='infocontact',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='review',
            name='username',
            field=models.CharField(max_length=150, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='sendmessage',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='sendmessage',
            name='text',
            field=models.TextField(max_length=550, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='sendmessage',
            name='username',
            field=models.CharField(max_length=155, verbose_name='Username'),
        ),
    ]
