# Generated by Django 5.2.8 on 2025-12-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0009_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgadmin',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tgadmin',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
