# Generated by Django 5.2.8 on 2025-12-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0010_alter_tgadmin_chat_id_alter_tgadmin_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocontact',
            name='address2_en',
            field=models.TextField(blank=True, null=True, verbose_name='Address2'),
        ),
        migrations.AddField(
            model_name='infocontact',
            name='address2_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Address2'),
        ),
        migrations.AddField(
            model_name='infocontact',
            name='address2_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Address2'),
        ),
        migrations.AddField(
            model_name='infocontact',
            name='address_en',
            field=models.TextField(null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='infocontact',
            name='address_ru',
            field=models.TextField(null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='infocontact',
            name='address_uz',
            field=models.TextField(null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='review',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='review',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='review',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='infocontact',
            name='address2',
            field=models.TextField(blank=True, verbose_name='Address2'),
        ),
    ]
