# Generated by Django 5.2.8 on 2025-12-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reliableservice',
            name='work_schedule',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
