# Generated by Django 5.2.8 on 2025-12-02 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_reliableservice_work_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'Biz haqimizda', 'verbose_name_plural': 'Biz haqimizda'},
        ),
        migrations.AlterModelOptions(
            name='additionalfeatures',
            options={'verbose_name': "Qoshimcha Ma'lumotlar", 'verbose_name_plural': "Qoshimcha Ma'lumotlar"},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': "Bo'lim", 'verbose_name_plural': "Bo'limlar"},
        ),
        migrations.AlterModelOptions(
            name='doctors',
            options={'verbose_name': 'Shifokor', 'verbose_name_plural': 'Shifokorlar'},
        ),
        migrations.AlterModelOptions(
            name='features',
            options={'verbose_name': "Kichik ma'lumot", 'verbose_name_plural': "Kichik Ma'lumotlar"},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Kasb', 'verbose_name_plural': 'Kasblar'},
        ),
        migrations.AlterModelOptions(
            name='reliableservice',
            options={'verbose_name': 'ishonchli xizmat', 'verbose_name_plural': 'ishonchli xizmatlar'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Xizmat', 'verbose_name_plural': 'Xizmatlar'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'Mutaxasislik', 'verbose_name_plural': 'Mutaxasisliklar'},
        ),
        migrations.AlterModelOptions(
            name='statistic',
            options={'verbose_name': 'Statistika', 'verbose_name_plural': 'Statistikalar'},
        ),
    ]
