# Generated by Django 5.2.8 on 2025-12-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_aboutus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='specialty',
        ),
        migrations.AddField(
            model_name='doctors',
            name='specialty',
            field=models.ManyToManyField(blank=True, to='blog.specialty'),
        ),
    ]
