# Generated by Django 5.2.8 on 2025-12-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_doctors_specialty_doctors_specialty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='features',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='features',
            field=models.JSONField(default=dict),
        ),
    ]
