# Generated by Django 5.2.8 on 2025-12-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_aboutus_features_aboutus_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='working_graph',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='features',
            field=models.TextField(blank=True),
        ),
    ]
