# Generated by Django 5.2.8 on 2025-12-03 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_aboutus_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reliableservice',
            name='work_schedule',
        ),
    ]
