# Generated by Django 5.2.8 on 2025-12-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_reliableservice_work_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='awards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistic',
            name='happy_patients',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
