# Generated by Django 5.2.8 on 2025-12-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_statistic_awards_statistic_happy_patients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='num_strollers',
            new_name='wheelchair',
        ),
    ]
