# Generated by Django 5.2.8 on 2025-12-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_num_strollers_statistic_wheelchair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
