# Generated by Django 5.2.8 on 2025-12-04 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='features_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='features_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='features_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_en',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_ru',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_uz',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='working_graph_en',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='working_graph_ru',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='working_graph_uz',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='additionalfeatures',
            name='description_en',
            field=models.TextField(max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='additionalfeatures',
            name='description_ru',
            field=models.TextField(max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='additionalfeatures',
            name='description_uz',
            field=models.TextField(max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=155, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='certificates_en',
            field=models.ManyToManyField(blank=True, null=True, to='blog.additionalfeatures'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='certificates_ru',
            field=models.ManyToManyField(blank=True, null=True, to='blog.additionalfeatures'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='certificates_uz',
            field=models.ManyToManyField(blank=True, null=True, to='blog.additionalfeatures'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='position_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.position'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='position_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.position'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='position_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.position'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='specialty_en',
            field=models.ManyToManyField(blank=True, null=True, to='blog.specialty'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='specialty_ru',
            field=models.ManyToManyField(blank=True, null=True, to='blog.specialty'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='specialty_uz',
            field=models.ManyToManyField(blank=True, null=True, to='blog.specialty'),
        ),
        migrations.AddField(
            model_name='features',
            name='name_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='features',
            name='name_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='features',
            name='name_uz',
            field=models.CharField(max_length=155, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='position',
            name='name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='position',
            name='name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='position',
            name='name_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='reliableservice',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='reliableservice',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='reliableservice',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='reliableservice',
            name='features_en',
            field=models.ManyToManyField(blank=True, null=True, to='blog.features'),
        ),
        migrations.AddField(
            model_name='reliableservice',
            name='features_ru',
            field=models.ManyToManyField(blank=True, null=True, to='blog.features'),
        ),
        migrations.AddField(
            model_name='reliableservice',
            name='features_uz',
            field=models.ManyToManyField(blank=True, null=True, to='blog.features'),
        ),
        migrations.AddField(
            model_name='reliableservice',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='reliableservice',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='reliableservice',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_uz',
            field=models.CharField(max_length=155, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='name_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='additionalfeatures',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=155, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='operations',
            field=models.CharField(max_length=150, verbose_name='Operations'),
        ),
        migrations.AlterField(
            model_name='features',
            name='name',
            field=models.CharField(max_length=155, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='reliableservice',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='reliableservice',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=155, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
    ]
