# Generated by Django 5.2.8 on 2025-12-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_aboutus_description_en_aboutus_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
