# Generated by Django 5.2.8 on 2025-12-06 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_doctors_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'lavozim', 'verbose_name_plural': 'lavozimlar'},
        ),
    ]
