# Generated by Django 5.2.8 on 2025-12-06 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_specialty_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'lavozim', 'verbose_name_plural': 'Lavozimlar'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'mutaxasislik', 'verbose_name_plural': 'mutaxasisliklar'},
        ),
    ]
