# Generated by Django 5.2.8 on 2025-12-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_position_options_alter_specialty_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='working_graph',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='working_graph_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='working_graph_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='working_graph_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
